{% set name = "sphinxcontrib-openapi" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c1bd10d7653912c59a42f727c62cbb7b75f7905ddd9ccc477ebfd1bc69f0cf3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15
  run:
    - python
    - sphinxcontrib-httpdomain >=1.5.0
    - PyYAML >=3.12
    - jsonschema >=2.5.1

test:
  imports:
    - sphinxcontrib.openapi

about:
  home: https://github.com/ikalnytskyi/sphinxcontrib-openapi
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Sphinx extension to generate APIs docs from OpenAPI (fka Swagger) spec.
  description: |
    sphinxcontrib-openapi is a Sphinx extension to generate APIs docs from
    OpenAPI (fka Swagger) spec. It depends on sphinxcontrib-httpdomain that
    provides an HTTP domain for describing RESTful HTTP APIs, so we don’t need
    to reinvent the wheel.
  doc_url: https://sphinxcontrib-openapi.readthedocs.io/
  dev_url: https://github.com/ikalnytskyi/sphinxcontrib-openapi

extra:
  recipe-maintainers:
    - carlodri
