travis:
  secure:
    BINSTAR_TOKEN: ssMe0MzZFYnhfmg9xmfhMny4TQjHNKfM6HU5PIf9r4w0f3h8xi8QEQgKa7ZeYv6XQoKaoQjaONbTb9oviFZJZELJHFgHMaMP9oIihrB7VaKVo77MZrI0cF5GztBp2Mv3Z34d+86FicYwZf4/3mApLvql3eh1YhHJcwgcOmXsVrCFQWNCRz7pUUnNj+DqMM8dmnq8GOV8N6cHcOl0OCV0IFD/x5iZOZE06U1R3BWFwns1UEnqt+eJeISq/WXg4qgBWXW2rdiO2l32ZDYJjPsUr0S3FrWKv4wmD7lKwDc0ykLPqYPTq2ud59GiIUgTe4p7EGURerYePMFqC2wfVISDbzyMatYvOHJRmAk1V1AVASDdukdYeRaaB7TFruEMbEumnL1zv8JVjDhCRvqh82xOg3Jj37oGGoih+TCSzYvWq1pq0g3CSuT+3ddeoyLjYSNuAfUVtRQ48MtDM3NVhVVPqeLtrwjBah/8LiJYuWWq14OXbeZVHFRllezNzREE32NtCKbLujLjdqFy4vvDnp43KirTxvb1H79l+BU93u9kso0HmN3n7Lk9WmsJLBz4N/rNFGOr0RU83p/AGzBu9zKz4JWrJqG6Yt3vepKh2+1OspvwD6lddKszvUmzZObeVvrpa+eF1HhrKCzRb4K6aLos+23V5S6RaKe7u1IFZ2z48F8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
